---
- hosts: all
  become: true
  tasks:

    - name: install vim and htop  package and update cache repository index
      dnf:
        name:
          - "{{ vim_package }}"
          - "{{ htop_package }} "
        state: latest
        update_cache: yes
