---
- hosts: all
  become: true
  tasks:

    - name: update_repository_index
      dnf:
        update_cache: yes

    - name: remove vim package
      dnf:
        name: vim
        state: absent

    - name: remove htop package
      dnf:
        name: htop
        state: absent

