---
- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


- hosts: linux_servers
  become: true
  tasks:
    - name: install vim and htop  package and update cache repository index
      tags: always
      dnf:
        name:
          - vim
          - htop
        state: latest
        update_cache: yes
      when: ansible_distribution == "Amazon"
      #when: ansible_distribution in ["Debian","Ubuntu"]
      #when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"
      
- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb
      tags: Amazon,mariadb
      dnf:
        name: mariadb105-server
        state: latest

- hosts: file_servers
  become: true
  tasks:
    - name: Install mariadb
      tags: Ubuntu,mariadb
      apt:
        name: mariadb-server
        state: latest

    - name: Install samba
      tags: Ubuntu,samba
      apt:
        name: samba
        state: latest

    - name: Copy default html file for site
      tags: Ubuntu,samba
      copy:
        src: default_site.html
        dest: /etc/www/index.html
        owner: root
        group: root
        mode: 0644


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.1/terraform_1.5.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root 


