---
- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


- hosts: linux_servers
  become: true
  tasks:
    - name: install vim and htop  package and update cache repository index
      dnf:
        name:
          - vim
          - htop
        state: latest
        update_cache: yes
      when: ansible_distribution == "Amazon"
      #when: ansible_distribution in ["Debian","Ubuntu"]
      #when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"
      
- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb
      dnf:
        name: mariadb105-server
        state: latest

- hosts: file_servers
  become: true
  tasks:
    - name: Install mariadb
      apt:
        name: mariadb-server
        state: latest
